### PR TITLE
Implement deserialization in BoolToIntConverter

### PR DESCRIPTION
**Pull request by vivan000**

### CODE REVIEW

**Comment by bytefish** [comment]
Thanks! Is it an urgent fix for you, that needs to be released or can it wait until the next Bugfix release? 🤠

**Comment by vivan000** [comment]
Yes, if it's possible - new release will help me a lot.
Thank you!

**Comment by bytefish** [comment]
Sure it's possible! I will try to do it as soon as possible.

**Comment by bytefish** [comment]
@vivan000 I have uploaded 2.8.4 to NuGet, which includes your changes! 👍 Thanks for your patience and sorry it took so long.

**Pull request merged**
