### PR TITLE
Added ConfigureAwait(false)

### PR DESCRIPTION
**Pull request by Sverdel**
In my case everything works good, when i send messages from desctop app. When I try to send message from web app (IIS hosted), SendAsync method hang up. ConfigureAwait(false) solve this problem.

### CODE REVIEW

**Comment by bytefish** [comment]
Thanks for your pull request. Just a question, the FcmClient allows to pass in a CancellationToken, which will be passed all the way down to the HttpClient. Can't you pass in a Token with the ConfigureAwait in your situation? 🤔

**Comment by bytefish** [comment]
If it is an MVC or Web API Project, can you use Asynchronous Actions? They should solve the problem effectively, without changing the code base.

**Comment by bytefish** [comment]
You know, I am trying to determine what are the effects of using ConfigureAwait(false) throughout the Code Base. I know the Problem with MVC, because the SynchronizationContext only allows 1 Thread and your await tries to continue on the SynchronizationContext... you are deadlocked.

**Comment by bytefish** [comment]
Hmmmm... I am reading through Stackoverflow Posts (https://stackoverflow.com/a/13489639/513875). I want to evaluate some more libraries and see what's best practice. Thanks for bringing up the issue! In the meantime, let me know if making the Controller Action an Async works for you.

**Comment by bytefish** [comment]
You know, of course I know the problems with ASP.NET and UI Code and where the Deadlocks can occur. The question to me is: What are the downsides of using ConfigureAwait(...) all the way down in the library?

**Comment by bytefish** [comment]
I looked into Microsoft SDKs and they also use ConfigureAwait(...) everywhere. So I will do this aswell, I will update the library and release a new version, when I get back to a Computer.

**Comment by Sverdel** [comment]
I've already tried to use async Controller Action before creating pull request. Unfortunately, it didn't solve thr problem. Thank you for the fast response! Will wait for new nuget package

**Comment by bytefish** [comment]
Can you tell me how you call the SendAsync method in your application? I want to add it to the README, so it is clear how to use it in a MVC Context. Do you also add ConfigureAwait(false)?

**Comment by bytefish** [comment]
I have released Version 2.3.0 to NuGet. Please let me know, if it fixes your problems. 👍

**Comment by bytefish** [comment]
@Sverdel Still maybe you can share an example on how you call the library, because it is something a lot of people might now know and it would be worth including a minimal sample in the README. I see that my example on how to do synchronous calls is probably very misleading.

**Comment by Sverdel** [comment]
New version fixes my problem. Thanks a lot! I'll send you an example soon

**Comment by Sverdel** [comment]
this is simple web api example, where a had deadlock with version 2.2.0. It is strange that in this example async action solve the problem, but in real project it didn't help. Perhaps, i'll make some research in my project later

```
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var configuration = new HttpConfiguration();
            configuration.MapHttpAttributeRoutes();

            app.UseWebApi(configuration);
        }
    }

    [RoutePrefix("v1/test")]
    public class TestController : ApiController
    {
        [HttpGet, Route("")]
        public IHttpActionResult Get()
        {
            // Read the Credentials from a File, which is not under Version Control:
            var settings = new FcmClientSettings("<project id>", "<credentials>");

            // Construct the Client:
            using (var client = new FcmClient(settings))
            {
                // Construct the Data Payload to send:
                var data = new Dictionary<string, string>()
                            {
                                {"A", "B"},
                                {"C", "D"}
                            };
                string registrationId = "<registration id>";

                // The Message should be sent to the given token:
                var message = new FcmMessage()
                {
                    ValidateOnly = false,
                    Message = new Message
                    {
                        Token = registrationId,
                        Data = data
                    }
                };

                // Finally send the Message and wait for the Result:
                CancellationTokenSource cts = new CancellationTokenSource();

                // Send the Message and wait synchronously:
                var result = client.SendAsync(message, cts.Token).GetAwaiter().GetResult();

                return Ok($"Message ID = {result.Name}");
            }
        }
    }
```

**Comment by bytefish** [comment]
Thanks!

**Comment by bytefish** [comment]
Maybe this is an ASP.NET Core Project? I read, that ASP.NET Core doesn't have a ``SynchronizationContext`` anymore, so ``ConfigureAwait`` has basically no effect there. If your real project is a MVC5 project, I am quite sure it behaves differently.

**Comment by Sverdel** [comment]
No, both projects are MVC5

**Comment by icebeam7** [comment]
I have a question. Does the token already include the topic? Because if I set both the token and topic in the Message, I receive an error: "Invalid value at 'message' (oneof), oneof field 'target' is already set. Cannot set 'topic'"

If I set the Topic only, the notification is not received by the device. It works when the Token is set alone.

**Pull request merged**
