### PR TITLE
Added a stream based way to load credentials

### PR DESCRIPTION
**Pull request by janniksam**
I built it for my own purpose (I save the json in my embedded resources).
Could be useful for other people aswell.

### CODE REVIEW

**Comment by bytefish** [comment]
@janniksam Thanks for your Pull Request! I will see what's the best way to integrate it. 😎

**Comment by janniksam** [comment]
It's my first pull request, so please have mercy with me :)

**Comment by bytefish** [comment]
No worries! Good work. 😎

**Comment by bytefish** [comment]
I just thought yesterday: There are probably a million more ways to read the Settings. And this "FileBased..." is too long for a human brain to remember. 😅 I would have to Google for an example each time I  use the library. An extension method doesn't fit. Maybe something like a ``SettingsUtils`` class with the static methods for reading from File or Stream.

**Comment by bytefish** [comment]
@janniksam What do you think would be the most intuitive way? Good API Design is hard. 🤔

**Comment by janniksam** [comment]
Unfortunately I am not that good at designing, I always have a bad feeling when it comes to that topic.

**But let me try:**
Just like you said, SettingsUtils sounds fine too me. But I don't like "Utils". "Utils" is like "Manager". It sounds like a class that tends to do alot of things instead of having one single purpose. In my opinion It breaks the principle "seperation of concerns". Maybe "Creator" would fit in this case.

One thing I saw in your code is, that your class is namemd FileBased.... and the method inside is called ReadFromFile or something like this. It's a personal preference, but I don't like that, I think it is redundant.

So, what you should do (imho):
- Create a SettingsCreator class.
- Create methods called:
---> CreateFromFile
---> CreateFromStream
---> CreateFromJson (accepting the json string

And last but not least,- I think it's self explanatory: 
- Do not delete your FileBased.... for the next few releases. It would break existing apps consuming your code. Instead mark it as "Obsolete("Use SettingsCreator") or similar. 

Sorry I didn't mean to write that much. ;)

**Comment by bytefish** [comment]
Thanks for your opinion! It's too late to remove the class anyway. 🤣 Deprecating it is a good idea for a soft upgrade path. Yes I didn't like this design, either... but then it was commited and too late. 😳 Creator sounds good, I will add this and deprecate the other method.

**Pull request merged**
