### PR TITLE
Better messaging error response, some documentation

### PR DESCRIPTION
**Pull request by sir-boformer**

### CODE REVIEW

**Comment by bytefish** [comment]
Good work! 😎 Please give me some time to take a look, before merging it.

**Comment by sir-boformer** [comment]
of course. I figured out a way with the existing `Dictionary`

**Comment by bytefish** [comment]
Just a question, I am reading the diff on the phone so I might be wrong.

Why is the content passed twice into the Exception:

* https://github.com/bytefish/FcmSharp/blob/d7f642241f6423b0c72f1fc9b47555bf8d47b9e4/FcmSharp/FcmSharp/FcmClient.cs#L98

Besides this everything looks good! 🤜🤛

**Comment by bytefish** [comment]
@sir-boformer If I merge it, what do you think about the version number of the library? Should it be a 3.0 then? Because some people might have built their error handling on the previous implementation, so this looks like a breaking change.

**Comment by bytefish** [comment]
Please don't be disappointed for me not merging yet! I will for sure, but I am hesitant to make breaking changes and go to 3.0 for now.

**Comment by bytefish** [comment]
@sir-boformer Thank you very, very much for your Pull Request. I always considered merging it in the past months, but I am still hesitant... just because I still don't know if I am interpreting the protocol correctly. This sucks a lot for users of the API... but at the same time I don't want API requests to fail, because I missed something in the docs and the deserialization fails. Sorry for closing and thanks again for your good support!

**Pull request closed without merging**
